#!/usr/bin/env python3

import glob
import subprocess

import ruamel.yaml
from ruamel.yaml.comments import CommentedSeq

if __name__ == "__main__":
    # get all helmfile.yaml files
    for helmfile_filename in glob.glob("**/helmfile.yaml", recursive=True):
        with open(helmfile_filename) as helmfile_file:
            helmfile = ruamel.yaml.YAML().load(helmfile_file)
        for release in helmfile["releases"]:
            comment = (
                release["values"]._yaml_comment
                if hasattr(release["values"], "_yaml_comment")
                else None
            )
            release["values"] = CommentedSeq(release["values"][::-1])
            if comment is not None:
                release["values"]._yaml_comment = comment
        with open(helmfile_filename, "w") as helmfile_file:
            ruamel.yaml.YAML().dump(helmfile, helmfile_file)
        subprocess.run(
            ["pre-commit", "run", "--files=" + helmfile_filename, "prettier"]
        )
